CREATE TABLE IF NOT EXISTS account (
id UUID NOT NULL PRIMARY KEY,
cardNumber VARCHAR(20) NOT NULL,
password VARCHAR (4) NOT NULL,
balance INTEGER NOT NULL
);
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";